work_dir: /content/drive/MyDrive/st-gcn-project/runs/kg_dynonly

# feeder
feeder: feeder.feeder.Feeder
num_worker: 0

train_feeder_args:
  data_path: /content/drive/MyDrive/st-gcn-project/datasets/ntu_processed/xsub/train_data.npy
  label_path: /content/drive/MyDrive/st-gcn-project/datasets/ntu_processed/xsub/train_label.pkl
  debug: False

test_feeder_args:
  data_path: /content/drive/MyDrive/st-gcn-project/datasets/ntu_processed/xsub/val_data.npy
  label_path: /content/drive/MyDrive/st-gcn-project/datasets/ntu_processed/xsub/val_label.pkl

# model — KG + Dynamic Adj only
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 120
  use_kg: True
  use_temporal_attention: False
  use_dynamic_adj: True
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# optimizer
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: [0]
batch_size: 16
test_batch_size: 16
num_epoch: 10
save_interval: 1
eval_interval: 2
log_interval: 100
